services:
  bg.yifen9.li:
    image: ghcr.io/yifen9/bg.yifen9.li
    container_name: bg.yifen9.li
    working_dir: /workspace
    ports:
      - "4321:4321"
    environment:
      - JULIA_DEPOT_PATH=/opt/julia-depot
    volumes:
      - "..:/workspace"
    command: >
      bash -lc "
        bun install &&
        bun run julia:deps &&
        bun run julia:setup &&
        bun run build &&
        exec sleep infinity
      "
